// <auto-generated />
namespace OMS.Migrations.StoreConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class twocontextreset1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(twocontextreset1));
        
        string IMigrationMetadata.Id
        {
            get { return "202008130558476_twocontextreset1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
